name: EasyBuild EESSI Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  ubuntu-minimal:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-24.04-arm
          - ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: eessi/github-action-eessi@v3
    - name: Test EESSI
      run: |
        module load EESSI-extend
        unset EASYBUILD_DEBUG
        eb --logtostdout build.eb --software-commit=f16864ee18ee86553f36c664c61c2ddf3b4fa1e2
      shell: bash
